(()=>{"use strict";
const C=window.STORE_STOCK_CONFIG,$=id=>document.getElementById(id);
let products=[],stores=[],sales=new Map(),baseMonday=monday(new Date()),through=addDays(new Date(),-1),importRows=null;
function d0(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function monday(d){const x=d0(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x}
function addDays(d,n){const x=d0(d);x.setDate(x.getDate()+n);return x}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function fmt(d){return iso(d).replaceAll("-","/")}
function parseDate(v){if(v==null||v==="")return null;if(v instanceof Date&&!isNaN(v))return d0(v);if(typeof v==="number"&&window.XLSX){const p=XLSX.SSF.parse_date_code(v);if(p)return new Date(p.y,p.m-1,p.d)}const m=String(v).trim().replace(/^"|"$/g,"").match(/^(\d{4})[\/\-](\d{1,2})[\/\-](\d{1,2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null}
function jan(v){let s=String(v??"").trim().replace(/^"|"$/g,"");return /^\d+\.0$/.test(s)?s.slice(0,-2):s}
function txt(v){return String(v??"").trim()}
function qty(v){const n=Number(String(v??"").replace(/,/g,"").trim());return Number.isFinite(n)?Math.trunc(n):0}
function key(j,s){return `${j}|||${s}`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function notice(m,t=""){const e=$("notice");if(!m){e.className="notice hidden";e.textContent="";return}e.className=`notice ${t}`;e.textContent=m}
function getAccessKey(){return localStorage.getItem(C.STORAGE_KEY)||""}
function setAccessKey(v){localStorage.setItem(C.STORAGE_KEY,v)}
function csvUrl(id,gid){return `https://docs.google.com/spreadsheets/d/${encodeURIComponent(id)}/gviz/tq?tqx=out:csv&gid=${encodeURIComponent(gid)}&t=${Date.now()}`}
function parseCSV(s){const rows=[];let row=[],f="",q=false;for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c==='"'){if(s[i+1]==='"'){f+='"';i++}else q=false}else f+=c}else{if(c==='"')q=true;else if(c===","){row.push(f);f=""}else if(c==="\n"){row.push(f);rows.push(row);row=[];f=""}else if(c!=="\r")f+=c}}row.push(f);if(row.some(v=>v!==""))rows.push(row);return rows}
async function fetchRows(id,gid,label){const r=await fetch(csvUrl(id,gid),{cache:"no-store"});if(!r.ok)throw new Error(`${label}: HTTP ${r.status}`);const t=await r.text();if(/^\s*</.test(t)||t.toLowerCase().includes("<html"))throw new Error(`${label}: GoogleシートをCSV取得できません。`);return parseCSV(t)}
function hidx(h,w){const z=txt(w).toLowerCase();return h.findIndex(x=>txt(x).toLowerCase()===z)}
function canon(h){const z=txt(h);for(const [k,a] of Object.entries(C.STORE_ALIASES||{}))if(a.some(x=>txt(x)===z))return k;return z}
function detectStores(headers){const salesStores=new Set(C.SALES_SHEETS.map(x=>x.store)),out=[];headers.forEach((h,i)=>{const c=canon(h);if(salesStores.has(c))out.push({store:c,index:i})});return out}
function jsonp(params){return new Promise((resolve,reject)=>{if(!C.API_URL)return reject(new Error("Apps Script API URLが未設定です。"));const cb=`__stockcb_${Date.now()}_${Math.floor(Math.random()*1e6)}`;let done=false;const script=document.createElement("script"),timer=setTimeout(()=>finish(new Error("月曜在庫APIがタイムアウトしました。")),20000);function finish(err,data){if(done)return;done=true;clearTimeout(timer);delete window[cb];script.remove();err?reject(err):resolve(data)}window[cb]=data=>finish(null,data);const qs=new URLSearchParams({...params,callback:cb,_:Date.now()});script.onerror=()=>finish(new Error("月曜在庫APIへ接続できません。"));script.src=`${C.API_URL}?${qs}`;document.head.appendChild(script)})}
async function loadStock(){const accessKey=getAccessKey();if(!accessKey)throw new Error("アクセスコードを入力してください。");$("stockStatus").textContent="読込中…";const data=await jsonp({action:"stock",key:accessKey});if(!data?.ok)throw new Error(data?.message||"月曜在庫APIの認証または読込に失敗しました。");if(data.baseDate!==iso(baseMonday))throw new Error(`月曜在庫が未更新です。保存中: ${data.baseDate||"なし"} / 必要: ${iso(baseMonday)}`);if(!Array.isArray(data.rows)||data.rows.length<2)throw new Error("月曜在庫データがありません。");const rows=data.rows,h=rows[0].map(txt),ix={jan:hidx(h,"JAN"),sku:hidx(h,"品番"),name:hidx(h,"品名")};if(Object.values(ix).some(i=>i<0))throw new Error("月曜在庫の必須見出し JAN / 品番 / 品名 が不足しています。");const sc=detectStores(h);if(!sc.length)throw new Error("対象店舗列を検出できません。");stores=sc.map(x=>x.store);products=[];for(let r=1;r<rows.length;r++){const row=rows[r],j=jan(row[ix.jan]),sku=txt(row[ix.sku]);if(!j||!sku)continue;const stock={};sc.forEach(s=>stock[s.store]=qty(row[s.index]));products.push({jan:j,sku,name:txt(row[ix.name]),stock})}if(!products.length)throw new Error("月曜在庫の商品を1件も読み込めませんでした。");$("stockStatus").textContent=`${products.length.toLocaleString()}商品 / ${stores.length}店舗`}
async function loadSales(){sales=new Map();$("salesStatus").textContent="読込中…";if(through<baseMonday){$("salesStatus").textContent=`${C.SALES_SHEETS.length}/${C.SALES_SHEETS.length}店舗 OK`;return}const rs=await Promise.allSettled(C.SALES_SHEETS.map(async s=>{const rows=await fetchRows(s.id,s.gid,s.store);for(const row of rows){if(row.length<6)continue;const j=jan(row[0]),sold=qty(row[2]),dt=parseDate(row[5]);if(!j||!dt||dt<baseMonday||dt>through)continue;const k=key(j,s.store);sales.set(k,(sales.get(k)||0)+sold)}}));const bad=[];rs.forEach((r,i)=>{if(r.status==="rejected")bad.push(C.SALES_SHEETS[i].store)});if(bad.length){$("salesStatus").textContent=`${C.SALES_SHEETS.length-bad.length}/${C.SALES_SHEETS.length}店舗`;throw new Error(`売上シート取得NG: ${bad.join("、")}`)}$("salesStatus").textContent=`${C.SALES_SHEETS.length}/${C.SALES_SHEETS.length}店舗 OK`}
function cur(p,s){const b=p.stock[s]||0,v=sales.get(key(p.jan,s))||0;return{base:b,sold:v,current:Math.max(0,b-v)}}
function render(){const q=$("searchInput").value.trim().toUpperCase(),only=$("inStockOnly").checked;if(!q){$("results").innerHTML='<div class="empty">品番を入力してください。</div>';$("resultCount").textContent="";return}let m=products.filter(p=>p.sku.toUpperCase().includes(q));if(only)m=m.filter(p=>stores.some(s=>cur(p,s).current>0));const total=m.length;m=m.slice(0,C.MAX_RESULTS||200);$("resultCount").textContent=total>m.length?`${total}件中${m.length}件表示`:`${total}件表示`;$("results").innerHTML=m.length?m.map(p=>`<article class="item"><div class="item-head"><div><div class="sku">${esc(p.sku)}</div><div class="name">${esc(p.name)}</div></div><div class="jan">JAN ${esc(p.jan)}</div></div><div class="table-wrap"><table><thead><tr>${stores.map(s=>`<th>${esc(s.replace("ららぽーと",""))}</th>`).join("")}</tr></thead><tbody><tr>${stores.map(s=>{const x=cur(p,s);return `<td class="${x.current>0?"":"zero"}"><div class="current">${x.current}</div><div class="detail">月曜 ${x.base} − 売れ ${x.sold}</div></td>`}).join("")}</tr></tbody></table></div></article>`).join(""):'<div class="empty">一致する品番がありません。</div>'}
async function loadAll(){$("searchInput").disabled=true;$("reloadBtn").disabled=true;notice("");baseMonday=monday(new Date());through=addDays(new Date(),-1);$("baseDate").textContent=`${fmt(baseMonday)}（月）`;$("salesThrough").textContent=through<baseMonday?"今週はまだ差引なし":`${fmt(through)}まで`;try{await loadStock()}catch(e){$("stockStatus").textContent="NG";$("salesStatus").textContent="待機";notice(e.message,"error");$("results").innerHTML='<div class="empty">月曜在庫を確認してください。</div>';$("reloadBtn").disabled=false;return}try{await loadSales()}catch(e){notice(`${e.message}\n売れ数が不完全になるため検索を停止しました。`,"error");$("results").innerHTML='<div class="empty">全売上シートが正常になるまで検索できません。</div>';$("reloadBtn").disabled=false;return}$("searchInput").disabled=false;$("reloadBtn").disabled=false;$("accessCard").classList.add("hidden");notice("データ読込OK。検索できます。","success");render()}
async function inspectExcel(){const f=$("stockFileInput").files[0];if(!f){notice("全店在庫Excelを選択してください。","error");return}try{const b=await f.arrayBuffer(),wb=XLSX.read(b,{type:"array",cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:false});if(rows.length<2)throw new Error("Excelにデータがありません。");const h=rows[0].map(txt),missing=C.REQUIRED_HEADERS.filter(x=>hidx(h,x)<0);if(missing.length)throw new Error(`必要な見出しがありません: ${missing.join(" / ")}`);const sc=detectStores(h);if(!sc.length)throw new Error("対象店舗列を検出できません。");importRows=rows;$("uploadStockBtn").disabled=false;$("importResult").classList.remove("hidden");$("importResult").textContent=`確認OK\nファイル: ${f.name}\n行数: ${rows.length.toLocaleString()}行（見出し含む）\n対象店舗: ${sc.map(x=>x.store).join(" / ")}\n基準日: ${iso(baseMonday)}（月）`}catch(e){importRows=null;$("uploadStockBtn").disabled=true;$("importResult").classList.remove("hidden");$("importResult").textContent=`確認NG\n${e.message}`}}
function uploadStock(){if(!importRows)return;const accessKey=getAccessKey();if(!accessKey){notice("先にアクセスコードを保存してください。","error");return}if(!C.API_URL){notice("Apps Script API URLが未設定です。","error");return}const payload=JSON.stringify({baseDate:iso(baseMonday),rows:importRows});if(payload.length>8_000_000){notice("Excelデータが大きすぎます。管理者に連絡してください。","error");return}$("uploadStockBtn").disabled=true;$("uploadProgress").classList.remove("hidden");const form=document.createElement("form");form.method="POST";form.action=C.API_URL;form.target="uploadFrame";form.style.display="none";for(const [name,value] of Object.entries({action:"upload",key:accessKey,origin:location.origin,payload})){const input=document.createElement("input");input.type="hidden";input.name=name;input.value=value;form.appendChild(input)}document.body.appendChild(form);form.submit();setTimeout(()=>form.remove(),1000)}
window.addEventListener("message",e=>{if(!e.data||e.data.type!=="STORESTOCK_UPLOAD")return;$("uploadProgress").classList.add("hidden");if(e.data.ok){notice(`月曜在庫を更新しました。${e.data.rows||0}行 / 基準日 ${e.data.baseDate}`,"success");importRows=null;$("uploadStockBtn").disabled=true;setTimeout(loadAll,700)}else{notice(`月曜在庫更新NG: ${e.data.message||"不明なエラー"}`,"error");$("uploadStockBtn").disabled=false}});
$("saveAccessKeyBtn").addEventListener("click",()=>{const v=$("accessKeyInput").value.trim();if(!v){notice("アクセスコードを入力してください。","error");return}setAccessKey(v);loadAll()});
$("searchInput").addEventListener("input",render);$("inStockOnly").addEventListener("change",render);$("reloadBtn").addEventListener("click",loadAll);$("inspectStockBtn").addEventListener("click",inspectExcel);$("uploadStockBtn").addEventListener("click",uploadStock);
const saved=getAccessKey();if(saved){$("accessKeyInput").value=saved;loadAll()}else{$("stockStatus").textContent="待機";$("salesStatus").textContent="待機";$("baseDate").textContent=`${fmt(baseMonday)}（月）`;$("salesThrough").textContent=through<baseMonday?"今週はまだ差引なし":`${fmt(through)}まで`;$("results").innerHTML='<div class="empty">アクセスコードを入力してください。</div>'}
window.StoreStockTestAPI={monday,jan,qty,parseDate,parseCSV,hidx,canon,detectStores,cur};
})();